.class public Lly/img/android/sdk/IMGLYEventAccessors;
.super Ljava/lang/Object;
.source "SourceFile"


# static fields
.field public static eventWrapper:Ljava/lang/Object;

.field public static typedEventWrapper:Ljava/util/HashMap;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/HashMap<",
            "Ljava/lang/Class<",
            "*>;",
            "Lly/img/android/pesdk/backend/model/EventAccessorInterface;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method static constructor <clinit>()V
    .locals 2

    const/4 v0, 0x1

    if-nez v0, :cond_0

    and-int/2addr v0, v0

    const/4 v0, 0x0

    if-eqz v0, :cond_1

    :cond_0
    const/4 v0, 0x1

    :cond_1
    const/4 v0, 0x0

    .line 1
    new-instance v0, Ljava/util/HashMap;

    .line 2
    .line 3
    invoke-direct {v0}, Ljava/util/HashMap;-><init>()V

    .line 4
    .line 5
    .line 6
    sput-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->eventWrapper:Ljava/lang/Object;

    .line 7
    .line 8
    sput-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 9
    .line 10
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_6f07b4e1e0e541bc8fc318bea287c754;->eventWrapper:Ljava/util/HashMap;

    .line 11
    .line 12
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 13
    .line 14
    .line 15
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 16
    .line 17
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_d4e203defc39cb735043fe1acf4a8705;->eventWrapper:Ljava/util/HashMap;

    .line 18
    .line 19
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 20
    .line 21
    .line 22
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 23
    .line 24
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_59958bec9044983bbc3497339c36013a;->eventWrapper:Ljava/util/HashMap;

    .line 25
    .line 26
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 27
    .line 28
    .line 29
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 30
    .line 31
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_77540c19ce90df0ae026715ca85b9480;->eventWrapper:Ljava/util/HashMap;

    .line 32
    .line 33
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 34
    .line 35
    .line 36
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 37
    .line 38
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_42582eed8a08e0b864607a53e5fbfae3;->eventWrapper:Ljava/util/HashMap;

    .line 39
    .line 40
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 41
    .line 42
    .line 43
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 44
    .line 45
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_5bbdf6280bcfdb82a37fe6d3e5f55d79;->eventWrapper:Ljava/util/HashMap;

    .line 46
    .line 47
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 48
    .line 49
    .line 50
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 51
    .line 52
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_d56234daee56d792daf33cd1d6762610;->eventWrapper:Ljava/util/HashMap;

    .line 53
    .line 54
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 55
    .line 56
    .line 57
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 58
    .line 59
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_0dbc4690cc453308db6871f593c01b01;->eventWrapper:Ljava/util/HashMap;

    .line 60
    .line 61
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 62
    .line 63
    .line 64
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 65
    .line 66
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_651ee854b4750305e5ac90460ba2a453;->eventWrapper:Ljava/util/HashMap;

    .line 67
    .line 68
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 69
    .line 70
    .line 71
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 72
    .line 73
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_118cd89856ecc0222c8dd9a7a17687a9;->eventWrapper:Ljava/util/HashMap;

    .line 74
    .line 75
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 76
    .line 77
    .line 78
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 79
    .line 80
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_ee254041c7cd18935512919df6371349;->eventWrapper:Ljava/util/HashMap;

    .line 81
    .line 82
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 83
    .line 84
    .line 85
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 86
    .line 87
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 88
    .line 89
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 90
    .line 91
    .line 92
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 93
    .line 94
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_a4b1c1f48d6a9411349f7275b171ab3f;->eventWrapper:Ljava/util/HashMap;

    .line 95
    .line 96
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 97
    .line 98
    .line 99
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 100
    .line 101
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_b03675d4e6c80750cdb36718ae81b4cc;->eventWrapper:Ljava/util/HashMap;

    .line 102
    .line 103
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 104
    .line 105
    .line 106
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 107
    .line 108
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_d3bff113e293d6a641bb38ef5cdfad49;->eventWrapper:Ljava/util/HashMap;

    .line 109
    .line 110
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 111
    .line 112
    .line 113
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 114
    .line 115
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_cfccc7289000ea352159e0bccecbcb2c;->eventWrapper:Ljava/util/HashMap;

    .line 116
    .line 117
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 118
    .line 119
    .line 120
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 121
    .line 122
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_e066f796fd1655b04db4a8b31a5d8d74;->eventWrapper:Ljava/util/HashMap;

    .line 123
    .line 124
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 125
    .line 126
    .line 127
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 128
    .line 129
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_cea9baaaab0a1fce3c6e626ba6a82069;->eventWrapper:Ljava/util/HashMap;

    .line 130
    .line 131
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 132
    .line 133
    .line 134
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 135
    .line 136
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_16b63c2b27ed74d4c3792be8a18c9160;->eventWrapper:Ljava/util/HashMap;

    .line 137
    .line 138
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 139
    .line 140
    .line 141
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 142
    .line 143
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_bbb86fec63f7aef232d6b126d8c2bd06;->eventWrapper:Ljava/util/HashMap;

    .line 144
    .line 145
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 146
    .line 147
    .line 148
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 149
    .line 150
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_d57cc7f9c1654634521224f951db5544;->eventWrapper:Ljava/util/HashMap;

    .line 151
    .line 152
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 153
    .line 154
    .line 155
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 156
    .line 157
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_a185e0f38a0bc64795d0664c3e840414;->eventWrapper:Ljava/util/HashMap;

    .line 158
    .line 159
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 160
    .line 161
    .line 162
    sget-object v0, Lly/img/android/sdk/IMGLYEventAccessors;->typedEventWrapper:Ljava/util/HashMap;

    .line 163
    .line 164
    sget-object v1, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_afa84b4e6e8044929df1e56882201407;->eventWrapper:Ljava/util/HashMap;

    .line 165
    .line 166
    invoke-virtual {v0, v1}, Ljava/util/HashMap;->putAll(Ljava/util/Map;)V

    .line 167
    .line 168
    .line 169
    return-void
.end method

.method public constructor <init>()V
    .locals 1

    const/4 v0, 0x1

    if-nez v0, :cond_0

    and-int/2addr v0, v0

    const/4 v0, 0x0

    if-eqz v0, :cond_1

    :cond_0
    const/4 v0, 0x1

    :cond_1
    const/4 v0, 0x0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static init(Ljava/lang/Object;)V
    .locals 1

    const/4 v0, 0x1

    if-nez v0, :cond_0

    and-int/2addr v0, v0

    const/4 v0, 0x0

    if-eqz v0, :cond_1

    :cond_0
    const/4 v0, 0x1

    :cond_1
    const/4 v0, 0x0

    invoke-static {p0}, Lly/img/internal/sdk_init/SDK_INIT;->init(Ljava/lang/Object;)V

    return-void
.end method

.method public static initUiStatePanels()V
    .locals 1

    const/4 v0, 0x1

    if-nez v0, :cond_0

    and-int/2addr v0, v0

    const/4 v0, 0x0

    if-eqz v0, :cond_1

    :cond_0
    const/4 v0, 0x1

    :cond_1
    const/4 v0, 0x0

    invoke-static {}, Lly/img/internal/sdk_init/SDK_INIT_UI_STATE;->init()V

    return-void
.end method
