.class public Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;
.super Ljava/lang/Object;
.source "SourceFile"


# static fields
.field public static eventWrapper:Ljava/util/HashMap;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/HashMap<",
            "Ljava/lang/Class<",
            "*>;",
            "Lly/img/android/pesdk/backend/model/EventAccessorInterface;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method static constructor <clinit>()V
    .locals 3

    const/4 v0, 0x1

    if-nez v0, :cond_0

    and-int/2addr v0, v0

    const/4 v0, 0x0

    if-eqz v0, :cond_1

    :cond_0
    const/4 v0, 0x1

    :cond_1
    const/4 v0, 0x0

    .line 1
    new-instance v0, Ljava/util/HashMap;

    .line 2
    .line 3
    invoke-direct {v0}, Ljava/util/HashMap;-><init>()V

    .line 4
    .line 5
    .line 6
    sput-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 7
    .line 8
    new-instance v1, Lly/img/android/pesdk/ui/model/state/$UiState_EventAccessor;

    .line 9
    .line 10
    invoke-direct {v1}, Lly/img/android/pesdk/ui/model/state/$UiState_EventAccessor;-><init>()V

    .line 11
    .line 12
    .line 13
    const-class v2, Lly/img/android/pesdk/ui/model/state/UiState;

    .line 14
    .line 15
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 16
    .line 17
    .line 18
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 19
    .line 20
    new-instance v1, Lly/img/android/pesdk/ui/model/state/$UiStateMenu_EventAccessor;

    .line 21
    .line 22
    invoke-direct {v1}, Lly/img/android/pesdk/ui/model/state/$UiStateMenu_EventAccessor;-><init>()V

    .line 23
    .line 24
    .line 25
    const-class v2, Lly/img/android/pesdk/ui/model/state/UiStateMenu;

    .line 26
    .line 27
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 28
    .line 29
    .line 30
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 31
    .line 32
    new-instance v1, Lly/img/android/pesdk/ui/panels/$ColorOptionToolPanel_EventAccessor;

    .line 33
    .line 34
    invoke-direct {v1}, Lly/img/android/pesdk/ui/panels/$ColorOptionToolPanel_EventAccessor;-><init>()V

    .line 35
    .line 36
    .line 37
    const-class v2, Lly/img/android/pesdk/ui/panels/ColorOptionToolPanel;

    .line 38
    .line 39
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 40
    .line 41
    .line 42
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 43
    .line 44
    new-instance v1, Lly/img/android/pesdk/ui/viewholder/$ColorViewHolder_EventAccessor;

    .line 45
    .line 46
    invoke-direct {v1}, Lly/img/android/pesdk/ui/viewholder/$ColorViewHolder_EventAccessor;-><init>()V

    .line 47
    .line 48
    .line 49
    const-class v2, Lly/img/android/pesdk/ui/viewholder/ColorViewHolder;

    .line 50
    .line 51
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 52
    .line 53
    .line 54
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 55
    .line 56
    new-instance v1, Lly/img/android/pesdk/ui/widgets/$EditorRootView_EventAccessor;

    .line 57
    .line 58
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/$EditorRootView_EventAccessor;-><init>()V

    .line 59
    .line 60
    .line 61
    const-class v2, Lly/img/android/pesdk/ui/widgets/EditorRootView;

    .line 62
    .line 63
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 64
    .line 65
    .line 66
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 67
    .line 68
    new-instance v1, Lly/img/android/pesdk/ui/widgets/$ImgLyTitleBar_EventAccessor;

    .line 69
    .line 70
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/$ImgLyTitleBar_EventAccessor;-><init>()V

    .line 71
    .line 72
    .line 73
    const-class v2, Lly/img/android/pesdk/ui/widgets/ImgLyTitleBar;

    .line 74
    .line 75
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 76
    .line 77
    .line 78
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 79
    .line 80
    new-instance v1, Lly/img/android/pesdk/ui/widgets/$ProgressView_EventAccessor;

    .line 81
    .line 82
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/$ProgressView_EventAccessor;-><init>()V

    .line 83
    .line 84
    .line 85
    const-class v2, Lly/img/android/pesdk/ui/widgets/ProgressView;

    .line 86
    .line 87
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 88
    .line 89
    .line 90
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 91
    .line 92
    new-instance v1, Lly/img/android/pesdk/ui/widgets/$ToolContainer_EventAccessor;

    .line 93
    .line 94
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/$ToolContainer_EventAccessor;-><init>()V

    .line 95
    .line 96
    .line 97
    const-class v2, Lly/img/android/pesdk/ui/widgets/ToolContainer;

    .line 98
    .line 99
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 100
    .line 101
    .line 102
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 103
    .line 104
    new-instance v1, Lly/img/android/pesdk/ui/widgets/buttons/$AcceptButton_EventAccessor;

    .line 105
    .line 106
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/buttons/$AcceptButton_EventAccessor;-><init>()V

    .line 107
    .line 108
    .line 109
    const-class v2, Lly/img/android/pesdk/ui/widgets/buttons/AcceptButton;

    .line 110
    .line 111
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 112
    .line 113
    .line 114
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 115
    .line 116
    new-instance v1, Lly/img/android/pesdk/ui/widgets/buttons/$AcceptTextButton_EventAccessor;

    .line 117
    .line 118
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/buttons/$AcceptTextButton_EventAccessor;-><init>()V

    .line 119
    .line 120
    .line 121
    const-class v2, Lly/img/android/pesdk/ui/widgets/buttons/AcceptTextButton;

    .line 122
    .line 123
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 124
    .line 125
    .line 126
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 127
    .line 128
    new-instance v1, Lly/img/android/pesdk/ui/widgets/buttons/$CancelButton_EventAccessor;

    .line 129
    .line 130
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/buttons/$CancelButton_EventAccessor;-><init>()V

    .line 131
    .line 132
    .line 133
    const-class v2, Lly/img/android/pesdk/ui/widgets/buttons/CancelButton;

    .line 134
    .line 135
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 136
    .line 137
    .line 138
    sget-object v0, Lly/img/autogenerated/sdk_event_accessors/AccessorCollection_25a0caa3470dbe2ccaf33922698d5e31;->eventWrapper:Ljava/util/HashMap;

    .line 139
    .line 140
    new-instance v1, Lly/img/android/pesdk/ui/widgets/buttons/$CancelTextButton_EventAccessor;

    .line 141
    .line 142
    invoke-direct {v1}, Lly/img/android/pesdk/ui/widgets/buttons/$CancelTextButton_EventAccessor;-><init>()V

    .line 143
    .line 144
    .line 145
    const-class v2, Lly/img/android/pesdk/ui/widgets/buttons/CancelTextButton;

    .line 146
    .line 147
    invoke-virtual {v0, v2, v1}, Ljava/util/HashMap;->put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;

    .line 148
    .line 149
    .line 150
    return-void
.end method

.method public constructor <init>()V
    .locals 1

    const/4 v0, 0x1

    if-nez v0, :cond_0

    and-int/2addr v0, v0

    const/4 v0, 0x0

    if-eqz v0, :cond_1

    :cond_0
    const/4 v0, 0x1

    :cond_1
    const/4 v0, 0x0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
